eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-01:1001/eureka/,http://eureka-server-02:1002/eureka/,http://eureka-server-03:1003/eureka/
server:
  port: 3002
spring:
  application:
    name: service-ribbon-hystrix