version: "2.1"
services:
  service-ribbon-01:
    image: service-ribbon-01
    hostname: service-ribbon-01
    networks:
      - eureka-net
    ports:
      - "3001:3001"

#
#  service-ribbon-hystrix:
#    image: service-ribbon-hystrix
#    hostname: service-ribbon-hystrix
#    networks:
#      - eureka-net
#    ports:
#      - "3002:3002"


#  service-feign-01:
#    image: service-feign-01
#    hostname: service-feign-01
#    networks:
#      - eureka-net
#    ports:
#      - "4001:4001"

#  service-feign-hystric:
#    image: service-feign-hystric
#    hostname: service-feign-hystric
#    networks:
#      - eureka-net
#    ports:
#      - "4002:4002"


#  service-zuul-01:
#    image: service-zuul-01
#    hostname: service-zuul-01
#    networks:
#      - eureka-net
#    ports:
#      - "5001:5001"


networks:
  eureka-net:
    driver: bridge