spring:
  application:
    name: eureka-server

server:
  port: 1003

eureka:
  server:
    enable-self-preservation: false  # 开发环境关掉保护机制,快速发现已经挂掉的服务，生产环境需要设置为true提升服务稳定性
  instance:
    hostname: eureka-server-03
    prefer-ip-address: false
    instance-id: eureka-server-03

  client:
    serviceUrl:
      defaultZone: http://eureka-server-01:1001/eureka/,http://eureka-server-02:1002/eureka/